### ISSUE TITLE
Template and Imagery pages

### ISSUE THREAD

**Issue by bnaolu** [Bixal/brand-guide#1]
Add content or resources for these pages.

Logo page:
- [x] Bleed guide
- [x] Logo and monograms for downloading

Templates:
- [x] Keynote
- [x] PowerPoint
- [x] Social Post
- [x] Adobe Library
- [x] Any instructions on how to use the templates/resources

Imagery/Photography:
- [x] Add guidelines for choosing photos

Images:
- [x] Continue to add and refer to the [Figma](https://www.figma.com/file/8wHb6ug5v61iPHMwGl59XQ/Brand-Design-Guide?node-id=146%3A2) frame to track images that we're including in the guide.

**Comment by karenrobersn** [comment]
Logo page
Adobe asset library, including bleed guide and assets that can be used in the website design is here: https://assets.adobe.com/public/0b60fc60-a474-4b51-40e8-1d5e1b0af038

Templates (wip)
Social post: https://www.figma.com/file/uSdGkDjy2OVLxlhp1NVzM4/Social-Media-Template?node-id=0%3A1

**Comment by karenrobersn** [comment]
Powerpoint (this will potentially move but I will make sure to keep the link updated) https://bixal365.sharepoint.com/:p:/g/EfPTLplrHSZAp8hMvkvS-y4BqfSoUka2Ro9kNV_vMXn_XA

**Comment by karenrobersn** [comment]
Keynote template: https://bixal365.sharepoint.com/Shared%20Documents/2020%20Rebrand%20Templates/Presentation%20Templates/Bixal_Keynote_Template_2021.key
