### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by demi-johnson** [Bixal/brand-guide#14]
Add a contact in the footer or something!
So that if people need anything specific or have questions, they have an easy, clear way to get answers.

**Comment by bnaolu** [comment]
Currently looks like this in the footer:

![Current contact information in the brand guide footer.](https://user-images.githubusercontent.com/52218695/147768773-33751524-96c8-4d92-9ac1-d00453f4b2b8.png)

Thoughts, questions, concerns? Open to anything.
