### ISSUE TITLE
Home page responsiveness

### ISSUE THREAD

**Issue by demi-johnson** [Bixal/brand-guide#26]
- change the 'Looking forward' 2 column text to 1 column in mobile view
- can the scroll buton for 'learn more about Bixal' be moved down below the header text in mobile and tablet view?

**Comment by bnaolu** [comment]
Adding this here for visibility:

- [ ] easy access to downloadables

**Comment by bnaolu** [comment]
- gotta do something about the responsiveness of the landing page and "view more" component.
