### ISSUE TITLE
Color Ratio (?)

### ISSUE THREAD

**Issue by demi-johnson** [Bixal/brand-guide#6]
The current brand guide includes color ratio percentages in a circle chart. For the new brand guide, we could instead define what primary and accent colors mean and how that can guide your usage. How can this be displayed?

**Comment by karenrobersn** [comment]
Guide created as an additional page here: https://www.figma.com/file/uSdGkDjy2OVLxlhp1NVzM4/Social-Media-Template?node-id=64%3A2
