### ISSUE TITLE
Typography Image

### ISSUE THREAD

**Issue by demi-johnson** [Bixal/brand-guide#8]
Improve the image of brand guide typography page

**Comment by karenrobersn** [comment]
![Misc_microsite_graphics](https://user-images.githubusercontent.com/94643641/146985751-de835faa-63aa-444c-8566-0fd8212ecf22.png)
![Misc_microsite_graphics2](https://user-images.githubusercontent.com/94643641/146985753-7c5b7b90-f51c-4929-931d-5a93afedf4c7.png)

**Comment by karenrobersn** [comment]
@demi-johnson I have attached the two PNGs to you
